### ISSUE TITLE
.NET报错：Encountered unmappable character.

### ISSUE THREAD

**Issue by Zingg7** [babalae/genshin-fishing-toy#11]
Hi 我的系统是Windows 11，.NET框架版本是4.8，鱼上钩后会报以下的错误
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Cannot marshal: Encountered unmappable character.
   at System.String.ConvertToAnsi(Byte* pbNativeBuffer, Int32 cbNativeBuffer, Boolean fBestFit, Boolean fThrowOnUnmappableChar)
   at System.StubHelpers.CSTRMarshaler.ConvertToNative(Int32 flags, String strManaged, IntPtr pNativeBuffer)
   at OpenCvSharp.Internal.NativeMethods.highgui_imshow(String winName, IntPtr mat)
   at OpenCvSharp.Cv2.ImShow(String winName, Mat mat)
   at GenshinAutoFish.Core.ImageRecognition.MatchWords(Bitmap img, ImageCapture capture, Boolean enableImShow) in D:\HuiPrograming\Projects\CSharp\genshin-fishing-toy\GenshinAutoFish\Core\ImageRecognition.cs:line 93
   at GenshinAutoFish.FormMain.timerCapture_Tick(Object sender, EventArgs e) in D:\HuiPrograming\Projects\CSharp\genshin-fishing-toy\GenshinAutoFish\FormMain.cs:line 140
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
请问应该怎么解决？感谢。

**Comment by huiyadanli** [comment]
看错误，是显示opencv自带的窗口的时候报错的。

去掉"显示识别窗口(Debug)"试试。
